volumes:
  node_modules:

services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/node/Dockerfile

    working_dir: /workspace

    ports:
      - "5173:5173"

    environment:
      - VITE_HOST=0.0.0.0

    volumes:
      # ソースコードはホストと共有
      - type: bind
        source: ./frontend
        target: /workspace

      # 依存は Docker volume で隔離
      - type: volume
        source: node_modules
        target: /workspace/node_modules

    command: npm run dev -- --host 0.0.0.0

    stdin_open: true
    tty: true
